In [1]:
import numpy as np

### Solving linear system of equations
x + y + z = 3 <br/>
2x + 3y + 7z = 0 <br/>
x + 3y - 2z = 17

In [2]:
A = np.array([[1,1,1],[2,3,7],[1,3,-2]])
A

array([[ 1,  1,  1],
       [ 2,  3,  7],
       [ 1,  3, -2]])

In [3]:
b = np.array([3,0,17])
b

array([ 3,  0, 17])

In [4]:
#Solving a linear system of equation
np.linalg.solve(A,b) #Pass augmented matrix

array([ 1.,  4., -2.])

In [5]:
#Rank of a matrix
np.linalg.matrix_rank(A)

3

In [6]:
D = np.array([[1,1,1],[2,3,7],[0,0,0]])
D

array([[1, 1, 1],
       [2, 3, 7],
       [0, 0, 0]])

In [7]:
np.linalg.matrix_rank(D)

2

### Eigen Value Problem

In [8]:
E = np.array([[-6,3],[4,5]])
E

array([[-6,  3],
       [ 4,  5]])

In [9]:
w, v = np.linalg.eig(E)

In [10]:
w #Eigenvalue

array([-7.,  6.])

In [11]:
v #Eigenvector

array([[-0.9486833 , -0.24253563],
       [ 0.31622777, -0.9701425 ]])

In [12]:
# Ev = wv

np.multiply(w,v)

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])

In [13]:
np.matmul(E,v)

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])