In [1]:
import numpy as np

In [2]:
#check if a value is scalar
np.isscalar(26)

True

In [3]:
np.isscalar(26.5)

True

In [4]:
np.isscalar(False)

True

In [5]:
np.isscalar([26]) # as it is a list it can hold multiple values

False

In [7]:
#Scalar Computations
s1 = 6
s2 = 4

print(s1+s2) #Addition
print(s1-s2) #Subtraction
print(s1*s2) #Multiplication
print(s1/s2) #Division
print(s1//s2)#Integer/Floor division

10
2
24
1.5
1


In [8]:
#Vector
a = [1,2,3]
a

[1, 2, 3]

In [9]:
a * 2 #Incorrect

[1, 2, 3, 1, 2, 3]

In [10]:
#Muliplying a vector by a scalar
np.array(a) * 2

array([2, 4, 6])

In [12]:
np.multiply(a,2)

array([2, 4, 6])

In [13]:
#Adding a vector by a scalar
np.array(a) + 2

array([3, 4, 5])

In [14]:
np.add(a,2)

array([3, 4, 5])

In [15]:
#Vector Subtraction
np.subtract(a,2)

array([-1,  0,  1])

In [16]:
np.array(a) - 2

array([-1,  0,  1])

In [18]:
#Multiple Vector
a = [10,15,18]
b = [11,23,45]

In [20]:
np.add(a,b)

array([21, 38, 63])

In [21]:
a = np.array([10,15,18])
b = np.array([11,23,45])

a - b # Subtraction

array([ -1,  -8, -27])

In [22]:
a + b

array([21, 38, 63])

In [23]:
np.subtract(a,b)

array([ -1,  -8, -27])

In [24]:
#Dot product of two vectors
np.dot(a,b)

1265

In [25]:
#Cross product of two vectors
np.cross(a,b)

array([ 261, -252,   65])

In [26]:
#Magnitude of a vector
np.linalg.norm(a)

25.475478405713993