In [1]:
import numpy as np

In [2]:
A = np.array([[3,4],[2,1]])
B = np.array([[1,5],[3,7]])
print('A:\n',A)
print('B:\n',B)

A:
 [[3 4]
 [2 1]]
B:
 [[1 5]
 [3 7]]


In [3]:
#Addition of Matrix
A + B

array([[4, 9],
       [5, 8]])

In [4]:
np.add(A,B)

array([[4, 9],
       [5, 8]])

In [5]:
#Subtraction of matrix
A - B

array([[ 2, -1],
       [-1, -6]])

In [6]:
np.subtract(A,B)

array([[ 2, -1],
       [-1, -6]])

In [7]:
A

array([[3, 4],
       [2, 1]])

In [8]:
#Scalar Multiplication
A * 2

array([[6, 8],
       [4, 2]])

In [9]:
A * 1/2

array([[1.5, 2. ],
       [1. , 0.5]])

In [10]:
np.multiply(A,2)

array([[6, 8],
       [4, 2]])

In [11]:
# Adding Scalar to a matrix
A + 2

array([[5, 6],
       [4, 3]])

In [12]:
np.add(A,2)

array([[5, 6],
       [4, 3]])

In [13]:
A - 2

array([[ 1,  2],
       [ 0, -1]])

In [14]:
np.subtract(A,2)

array([[ 1,  2],
       [ 0, -1]])

In [15]:
#Two Matrices
print('A:\n',A)
print('B:\n',B)

A:
 [[3 4]
 [2 1]]
B:
 [[1 5]
 [3 7]]


In [16]:
A * B #This is not matrix multiplication

array([[ 3, 20],
       [ 6,  7]])

In [17]:
np.multiply(A,B) #This is not matrix multiplication

array([[ 3, 20],
       [ 6,  7]])

In [18]:
#Matrix Multiplication
np.matmul(A,B)

array([[15, 43],
       [ 5, 17]])

In [19]:
#Matrix Multiplication Example
C = np.array([[3,4,2]])
D = np.array([[13,9,7,15],[8,7,4,6],[6,4,0,3]])
print('C:\n',C, 'Shape: ', C.shape)
print('D:\n',D, 'Shape: ', D.shape)

C:
 [[3 4 2]] Shape:  (1, 3)
D:
 [[13  9  7 15]
 [ 8  7  4  6]
 [ 6  4  0  3]] Shape:  (3, 4)


In [20]:
np.matmul(C,D)

array([[83, 63, 37, 75]])

In [21]:
#Matrix Multiplication is not commutative EF != FE
E = np.array([[1,1],[100,100]])
F = np.array([[-1,1],[1,-1]])
np.matmul(E,F)

array([[0, 0],
       [0, 0]])

In [22]:
np.matmul(F,E)

array([[ 99,  99],
       [-99, -99]])

In [23]:
A

array([[3, 4],
       [2, 1]])

In [24]:
#Matrix Transpose
np.transpose(A)

array([[3, 2],
       [4, 1]])

In [25]:
A.T

array([[3, 2],
       [4, 1]])

In [26]:
A

array([[3, 4],
       [2, 1]])

In [27]:
np.transpose(np.transpose(A)) # Two times tanspose gives the actual matrix

array([[3, 4],
       [2, 1]])

### Transposition Rule
#### (AB)T = BT x AT
Here T stands for transpose

In [28]:
print('A:\n',A)
print('B:\n',B)

A:
 [[3 4]
 [2 1]]
B:
 [[1 5]
 [3 7]]


In [29]:
matrix_mul = np.matmul(A,B)
matrix_mul.T

array([[15,  5],
       [43, 17]])

In [30]:
np.matmul(B.T, A.T) #As per rule this is correct

array([[15,  5],
       [43, 17]])

In [31]:
np.matmul(A.T, B.T) #As per rule this is incorrect

array([[13, 23],
       [ 9, 19]])

### Special Matrices

In [32]:
#Symmetric
sMatrix = np.array([[1,1,-1],[1,2,0],[-1,0,5]])
sMatrix

array([[ 1,  1, -1],
       [ 1,  2,  0],
       [-1,  0,  5]])

In [33]:
sMatrix.T #Matrix transpose gives us the same matrix as it is symmetric matrix. aij = aji

array([[ 1,  1, -1],
       [ 1,  2,  0],
       [-1,  0,  5]])

In [34]:
#Skew Symmetric Matrix
ssMatrix = np.array([[0,1,-2],[-1,0,3],[2,-3,0]])
ssMatrix

array([[ 0,  1, -2],
       [-1,  0,  3],
       [ 2, -3,  0]])

In [35]:
ssMatrix.T #Matrix transpose gives us the same neative matrix as it is skew symmetric matrix. aij = -aji

array([[ 0, -1,  2],
       [ 1,  0, -3],
       [-2,  3,  0]])

In [36]:
#Diagonal Matrix
dMatrix = np.array([[12,0,0],[0,18,0],[0,0,26]])
dMatrix

array([[12,  0,  0],
       [ 0, 18,  0],
       [ 0,  0, 26]])

In [37]:
#Convert a vector to a diagonal matrix
a = np.array([12,18,26])
np.diag(a)

array([[12,  0,  0],
       [ 0, 18,  0],
       [ 0,  0, 26]])

In [38]:
#Finding determinant of a matrix
mat = np.array([[3,1],[1,2]])
mat

array([[3, 1],
       [1, 2]])

In [39]:
np.linalg.det(mat)

5.000000000000001

In [46]:
mat2 = np.array([[2,-3,1],[2,0,-1],[1,4,5]])
mat2

array([[ 2, -3,  1],
       [ 2,  0, -1],
       [ 1,  4,  5]])

In [48]:
sol = np.linalg.det(mat2)
sol

49.000000000000014

In [49]:
np.around(sol) #Rounding array values

49.0

In [50]:
np.linalg.det(mat.T)

5.000000000000001

In [51]:
A

array([[3, 4],
       [2, 1]])

In [52]:
id_mat = np.array([[1,0],[0,1]])
id_mat

array([[1, 0],
       [0, 1]])

In [53]:
np.matmul(A,id_mat)

array([[3, 4],
       [2, 1]])

In [54]:
#Inverse of a matrix
A_inv = np.linalg.inv(A)
A_inv

array([[-0.2,  0.8],
       [ 0.4, -0.6]])

In [55]:
# A x A_inv = I
np.matmul(A,A_inv)

array([[ 1.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00]])